server:
  port: 7001

spring:
  application:
    name: microservice-zuul-gateway

eureka:
  client:
    register-with-eureka: true # 服务注册开关
    fetch-registry: true # 服务发现开关
    service-url: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      defaultZone: http://eureka6002.com:6002/eureka,http://eureka6001.com:6001/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true # 访问路径显示ip地址

zuul:
  routes:
    product-hystrix-provider:
      path: /product/** # 访问路径
      serviceId: microservice-product-provider #指定服务ID(即提供者的spring.application.name)，会自动从Eureka中找到此服务的ip和端口
      stripPrefix: false  # 代理转发时去掉前缀，false:代理转发时不去掉前缀 例如:为true时 请求 /product/get/1，代理转发到/get/1